object Versions {
    const val androidGradle = "7.2.2"
    const val kotlinGradle = "1.7.10"
    const val hiltGradle = "2.42"
    const val compose = "1.3.0"
    const val composeLib = "1.2.1"
    const val composeNav = "2.5.1"
    const val ktor = "2.0.3"
    const val hilt = "2.43"
    const val hiltCompose = "1.0.0"
    const val androidLifecycle = "2.5.0"
    const val coroutines = "1.6.1"
    const val landscapist = "1.6.1"
    const val browser = "1.4.0"
    const val room = "2.4.3"
}
